rishabkumar7/cloud-resume-api

submissions.md

Tomiwa Aribisala Cloud Resume Api hosted on AWS

cloud-resume-api hosted on AWS

---

docs/submissions.md

Added my Resume API and GitHub Repo URLs to submissions.md file.

Update Azure submissions

---

docs/submissions.md

I completed the cloud-resume-api challenge in GCP Instead of GitHub Actions, I used CloudBuild. 
A project where I built and deployed a serverless API using Google Cloud Functions and Firestore, integrated with Cloud Build as CI/CD to deploy functions on every push to GitHub automatically. An API that can serve resume data in JSON format. I used Terraform to manage and provision cloud infrastructure.
Thanks!

GCP-cloud-resume-api

---

docs/submissions.md

I am pleased to submit my Cloud Resume Challenge project for review. This submission includes the following components:
- 3 serverless backend functions using AWS Lambda and API Gateway.
- Infrastructure as Code (IaC) using AWS CloudFormation and SAM framework
- Continuous integration and deployment (CI/CD) pipeline using GitHub Actions
Please review the changes and provide your feedback. I look forward to any suggestions for improvement.
Thank you!

ADDED Hein Htet Win submission

---

docs/submissions.md

This marks the completion of my project, as I am now learning things about GCP and studying for the ACE. This project will become my main project for completing cloud resume challenges for multiple CSPs that have Terraform support.
- Logging Header Data from Users who trigger the API into Cloud Firestore
- Automatic deployment and provisioning with Terraform using GitHub Actions and Terraform Cloud
- Linting, Format, and Terraform Plan GitHub Action executes when a PR is raised.
Let me know if you have any questions.

GCP Cloud Resume Challenge API - Damien's Submission

---

docs/submissions.md

This PR highlights my completion of the Cloud Resume API Challenge. Please find my deployed function URL below:
<a href="https://us-central1-vn-cloud-resume-api-challenge.cloudfunctions.net/cloud-resume-function">Deployed Function Link</a>
Deployed Cloud Function - Link should be publicly available.
Use of GitHub Actions - Visible in the files (Used every time a new change is pushed to rebuild Terraform resources).
FireStore Table - Included within the Terraform code, along with other resources.
These are included within <a href="https://github.com/vikramnayyarcs/vn-cloud-resume-api-challenge/blob/main/README.md#future-work">My Repo's</a> `README.md` file
I've seen on LinkedIn, as well as one of the previous Pull Requests that some people included their social media links therefore I …

GCP Cloud Resume API Challenge Solution - Vikram Nayyar

---

docs/submissions.md

I just want to submit again with updated custom domain name for Cloud Resume challenge. In this submission I've used AWS as hosting platform for deployment of serverless services and API Gateway. GitHub actions for CI/CD workflow.

Hein Htet Win - Submission for Cloud Resume Challenge

---

README.md
docs/submissions.md

```zsh
aws dynamodb put-item \
--table-name resume_json \
--item file://resume.json
```
```zsh
aws dynamodb get-item \
--table-name resume_json \
--key '{"resumeid": {"N": "1"}}' \
--projection-expression "resumedetails.basics","resumedetails.education","resumedetails.awards","resumedetails.certifications","resumedetails.skills","resumedetails.works"
```

Update submissions Suryendu .md

---

docs/submissions.md

Name - Meghana Sai Vattikuti 
I built a serverless API using AWS Lambda, DynamoDB, and API Gateway along with CloudWatch Logs enabled for my Lambda Function. I also automated the process of updating resume data in DynamoDB using GitHub Actions. To streamline the setup, I leveraged Terraform to manage all my infrastructure as code, eliminating the need to manually configure resources in the AWS console. This setup means my resume data gets updated seamlessly whenever I push changes to my repository, and I can manage my infrastructure efficiently with clear separation between provisioning and deployment. 
Additional Features: 
I automated the process of updating resume data in DynamoDB using GitHub Actions.
Additionally, I used Terraform to manage the infrastructure as code, ensuring a …

Submission to the Cloud Resume API Challenge

---

docs/submissions.md

- The way I implemented the solution for this challenge is by setting up an HTTP API using **API Gateway** which will trigger the Lambda function to get the data from Dynamo DB.
- We have to create an IAM Lambda execution role and attach it to the lambda function which allows our function runtime to interact with Dynamo DB to the get the data.
- Users can access the API Gateway endpoint(https) deployment link which will trigger the lambda function to get the resume data from dynamoDB
**New functionality:** 
In my solution I have introduced API Gateway for managing the apis for different versions(aka stages) for `DEV`, `QA`, `PROD` environments. We can maintain different versions of lambda functions and map it back to API Gateway by passing the lambda function version and deploying it on …

[rohit1101]/AWS submissions.md

---

docs/submissions.md

I built a Cloud Resume API called Resume Fetcher API using AWS Lambda, DynamoDB, and Terraform. The Lambda function retrieves resume data from a DynamoDB table, accessible via a Function URL. Terraform was used for infrastructure management, and GitHub Actions automates the deployment process. curl was used for testing the API. The project demonstrates serverless architecture, Infrastructure as Code, and CI/CD automation.
Toyyib Muhammad-Jamiu

Toyyib's AWS Cloud Resume API Challenge

---

docs/submissions.md

- I added my submission plus I added the | at the end of other submissions that didn't have it.
- **Services I used**
api-gateway
Lambda
DynamoDB
Terraform
Github Actions

submission

---

docs/submissions.md

My cloud resume api challenge submission

Godson Chinonyerem cLoud resume submission

---

docs/submissions.md

this is my cloud resume api challenge solution in aws

Meriem terki submission

---

docs/submissions.md

A serverless API using `Azure Functions` to fetch resume data from `CosmosDB`.
- Implemented complete infrastructure as code using `Terraform` 
- Seperate automated CI/CD pipelines for infrastructure and function code deployments
- *Key-feature*: Add support for **THEMED JSON Resume**. [Live Demo](https://resume26hamitfunc.azurewebsites.net/hamitsehjal)

Add entry to submissions.md

---

docs/submissions.md

This pull request demonstrates a serverless architecture for a Resume API using AWS services. It leverages AWS Lambda to process requests, AWS DynamoDB to store resume data, and AWS API Gateway to provide a RESTful endpoint for data retrieval. The API’s responses are delivered in JSON format. AWS S3 hosts and serves the static React front-end, with AWS CloudFront ensuring fast and secure content delivery. The deployment process is streamlined with GitHub Actions for automated CI/CD, and infrastructure is managed using Terraform Cloud for efficient resource provisioning and management.
1. AWS DynamoDB
2. AWS Lambda Function
3. AWS API gateway
4. AWS S3
5. AWS CloudFront
6. Terraform Cloud
7. Github actions

resume API challenge submission

---

docs/submissions.md

This Pull Request introduces my submission of the Cloud Resume API challenge, a serverless API solution built with AWS Lambda and DynamoDB, and integrated with GitHub Actions for continuous deployment. The project demonstrates how to serve resume data in JSON format using a Lambda function, with automated deployment pipelines that ensure updates are seamlessly pushed to AWS.
**Services Used**
AWS Lambda: Executes the serverless function that fetches resume data from DynamoDB.
Amazon DynamoDB: Stores the resume data in a NoSQL database.
API Gateway: Exposes the Lambda function as a web API endpoint.
Amazon ECR: Hosts the Docker image for the Lambda function.
GitHub Actions: Automates the build, deployment, and testing processes.
Terraform: Manages the infrastructure as code for creating …

ADD: Emmanuel Nyame Cromwell submitted for AWS

---

docs/submissions.md

This pull request is a solution to the cloud resume challenge. It involves deploying an AWS serverless API using AWS Lambda and Dynamodb, and integrating it with GitHub actions. The lambda function retrieves resume data from a DynamoDB table and returns it in JSON format. GitHub actions are used as the CI/CD pipeline to enable automated deployment. Terraform Cloud is used for resource provisioning and management of the cloud infrastructure. The resume data can be accessed using the Amazon API Gateway endpoint. 
AWS Dynamodb, AWS lambda, AWS API Gateway, Terraform and GitHub Actions

Submission for aws cloud resume api challenge

---

README.md

This is to fix the submission link on README page

submission link at README page

---

docs/submissions.md

This project implements a cloud-based resume using various AWS services, including AWS API Gateway, DynamoDB, Lambda functions, and Amazon S3. The goal is to create a robust and scalable resume application that can be easily updated and accessed via an API.
- API gateway
- Amazon DynamoDB
- Amazon S3
- AWS Lambda function
- CI/CD pipeline
- VS Code

aws cloud api challenge url submission

---

docs/submissions.md

This pull request illustrates a serverless architecture for a Resume API utilizing AWS Lambda and DynamoDB. The Lambda function fetches resume data from DynamoDB and returns it in JSON format. The setup includes GitHub Actions for automated deployment and Terraform Cloud for infrastructure management and resource provisioning.
AWS API Gateway
AWS Lambda
AWS DynamoDB
Github action
Terraform

new submissions

---

docs/submissions.md

This Project is my submission for the Cloud Resume API Challenge using Google Cloud Platform (GCP). It features a serverless function that fetches resume data from a NoSQL database and returns it in JSON format. GitHub Actions are integrated for automatic deployment, ensuring seamless updates with each code push.
Special thanks to Rishab for creating this challenge, which provides a hands-on opportunity to build a serverless API and integrate CI/CD pipelines with GitHub Actions.
1. Cloud Functions
2. Firestore
3. Cloud IAM (Identity and Access Management)
4. Apigee API Mangement
5. GitHub Actions
**Demo URL**
```
https://34.107.250.32.nip.io/resume
```
**Sample Response**
**Sample Quota Exceeded Response**
The quota policy is set to 10 requests per minute in the Apigee proxy. If the quota …

Add Suraj contribution to the challenge

---

docs/submissions.md

Added my submission 
Have created the aws infra using terraform script and ran the script through github actions for all the bonus points  Added a extra feature of having a post/put resume functionality on the same api gateway through another function  Looking forward to more such community creative projects to up skill all foks.
Aws api gateway 
Dynammo Db 
Lambda 
Iam for policys and Roles
In the readme file of my repo have 3 screenshots one for architecture similar to most folks and 2 for the extra features

Update submissions.md added raunak submission

---

docs/submissions.md

This project involves creating a serverless resume API using Azure Functions and CosmosDB, integrated with GitHub Actions for automated deployments. The API serves resume data in JSON format and features advanced capabilities such as language and section filtering, theming, pagination, and visitor tracking. The default response has been upgraded from plain text to an HTML page, providing a more interactive and user-friendly experience.
- **Language and Section Filtering**: Retrieve resume data based on language and specific sections.
- **Theming Options**: Apply themes such as a minimal design for a streamlined presentation.
- **Pagination**: Manage the display of work experience entries with pagination.
- **Visitor Tracking**: Track visitor counts and include metadata in the response.
- …

Added my submission to submissions.md

---

docs/submissions.md

My Azure student subscription expired on August 5. As a result, I created a new API and updated the link for that API in submissions.md

I updated the link to my Resume API inside submissions.md

---

docs/submissions.md

Created an API gateway and lambda function on AWS to deploy a json resume. This project used serverless architecture to serve the json acress the web.
AWS lambda
AWS API gateway
AWS Dynamo db
Terraform
Github actions
VsCode

Wanjuri Submission to the Cloud Resume API Challenge

---

docs/submissions.md

This is a pull request where a serverless Resume API is built and deployed using AWS resources. Here, an AWS Lambda function fetches resume data from an Amazon DynamoDB table, and returns it in JSON format. GitHub Actions is also integrated to automatically deploy changes to the AWS Lambda function on every push to your repository.
AWS Lambda
AWS DynamoDB
AWS API Gateway
GitHub Actions
Terraform

project submission-Rosemary Ojwang

---

docs/submissions.md

This Project focuses on building and deploying a serverless API that servers resume data in json format.
- DynamoDB Table created that contains my resume data.
- Lambda Function created that Fetches and returns resume data based on an id.
- API Gateway: Integrated an API Gateway for the Lambda Function to make you Lambda Function accessible.
- GitHub Actions: that automatically packages and deploys the Lambda function on every push to the repository.
- Terraform Modules - that build the whole infrastructure

Add Linet-Kendi-submission Details

---

docs/submissions.md

This project showcases a fully functional Google Cloud Function (GCF) that serves as an API endpoint to fetch resume data stored in a Firestore database. It retrieves the data upon receiving HTTP requests and transforms it into a well-structured JSON format for easy consumption by external applications. Additionally, the project implements a robust CI/CD pipeline using GitHub Actions, ensuring automated deployment and integration updates whenever changes are pushed to the repository.
**Key Components:**
Google Cloud Function (GCF): The core component responsible for handling HTTP requests, interacting with Firestore to retrieve resume data, and returning it as a JSON response.
Firestore Database: A NoSQL database service within GCP that serves as the primary storage for resume …

Nitish-GCP-Resume-API-Challenge Submission

---

docs/submissions.md

- **Name:** Joseph A Leto
- **GitHub Repo URL:** https://github.com/serversorcerer/Cloud-Resume-API-Challenge
- **Resume API URL:** https://5yw6uexaub.execute-api.us-east-1.amazonaws.com/Prod/resume
- **Medium Article:**
I have completed the Cloud Resume API Challenge. My project includes the following features:
- Serverless architecture using AWS Lambda and API Gateway
- Data storage in Amazon DynamoDB
- Infrastructure as Code with Terraform
- Automated CI/CD pipeline with GitHub Actions

Added my submission to the Submissions table
